#! /bin/bash
# return the biggest cluster

usage ()
{
	echo "Usage: $(basename $0) [-t THRESH] [-o OUT] -i IN"
	echo "  -i IN        input image"
	echo "  -o OUT       output image (default IN_cluster)"
	echo "  -t THRESH    threshold (default 1)"
	echo "  -f           fill holes"
	echo
}


while getopts i:o:t:fv opt
do
	case "$opt" in
		i)  IN="`imglob $OPTARG`";;
		t)  THRESH="$OPTARG";;
		f)  FILL=1;;
		v)  VERBOSE=1;;
		\?)  usage; exit 1;;
	esac
done
shift $(expr $OPTIND - 1)

[ -z "$IN" ] && { usage; echo "ERROR: input image not specified"; exit 1; }

THRESH=${THRESH:-1}
OUT=${OUT:-${IN}_cluster}

N=`cluster -i $IN -t $THRESH -o $OUT | awk 'NR==2 {print $1}'`
fslmaths $OUT -thr $N -bin $OUT


# fill holes

if [ "$FILL" = 1 ]; then
	fslmaths $OUT -bin -mul -1 -add 1 $OUT
	N=`cluster -i $OUT -t 1 -o $OUT | awk 'NR==2 {print $1}'`
	fslmaths $OUT -thr $N -bin -mul -1 -add 1 $OUT
fi


exit 0

