#! /bin/bash
# clean up sge error and output files in the present directory

FILES=`find . -maxdepth 1 -regex '.*\.[eo][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'`

echo $FILES | column -t
echo "found `echo $FILES | wc -w` files"
echo "press any button to remove these files (ctrl-c to abort)"
read

rm -v $FILES

