#! /bin/bash
# concatenate PDF files

usage ()
{
	echo "Usage: $(basename $0) OUTPUT PDFFILE.."
	echo "explanation"
}

[ $# -lt 2 ] && { usage; exit 1; }

OUT=$1; shift

gs -q -sPAPERSIZE=letter -dNOPAUSE -dBATCH -sDEVICE=pdfwrite -sOutputFile=$OUT $@


