#! /bin/bash
# concatenate PDF files

usage ()
{
	echo "Usage: $(basename $0) OUTPUT PDFFILE.."
	echo "  OUTPUT   name of output file"
    echo "  PDFFILE  two or more PDF files to be concatenated"
}

[ $# -lt 3 ] && { usage; exit 1; }

OUT=$1; shift

gs -q -sPAPERSIZE=letter -dNOPAUSE -dBATCH -sDEVICE=pdfwrite -sOutputFile=$OUT $@


