#! /bin/bash
#convert mat files between fsl and minc

usage ()
{
	echo "Usage: $(basename $0) INMAT"
	echo "INMAT   either FSL or MINC format .mat/.xfm file"
}


while getopts i:v opt
do
	case "$opt" in
		v)  VERBOSE=1;;
		\?)  usage; exit 1;;
	esac
done
shift $(expr $OPTIND - 1)

[ $# -lt 1 ] && { usage; exit 1; }

if [ "`head -n1 $1`" = "MNI Transform File" ]; then
	tail -n3 $1 | sed -e 's/;$//g'
else
cat <<EOF
MNI Transform File

Transform_Type = Linear;
Linear_Transform =
EOF
sed -e '$s/$/;/' $1
#sed -i -e '$s/$/;/' $2
fi

