#! /bin/bash
# wrapper for fslview, so it opens MINC files


usage ()
{
	echo "Usage: $(basename $0) IMAGE.."
	echo "  IMAGE            one or several images MINC or NIFTI"
}

cond_convert ()
{
	mincinfo $1 > /dev/null 2> /dev/null && { [ -z "$VERBOSE" ] || echo "converting $1"; mncconvert $1 $2 &> /dev/null; return; }
	fslinfo  $1 > /dev/null && {       imcp $1 $2;              return; }
	echo "ERROR: could not open file: $1"; exit 1
}



###############################################################################
# MAIN
###############################################################################


while getopts v opt
do
    case "$opt" in
      v)    VERBOSE="-v";;
      \?)  usage; exit 1;;
    esac
done
shift `expr $OPTIND - 1`

[ $# -lt 1 ] && { usage; exit 1; }

which mncconvert > /dev/null || { echo "ERROR: could not find mncconvert"; exit 1; }


TDIR=$TMPDIR/$$; mkdir -p $TDIR
trap "{ rm -fr $TDIR; echo 'cleaned up temp. directory'; exit 255; }" SIGTERM SIGINT


IN=; i=0
for f in $@; do
	g=$TDIR/`printf "%03i_%s" $i $(basename $f .mnc)`
	cond_convert $f $g
	IN="$IN $g"
	let i++
done

fslview $IN

rm -r $TDIR
exit 0


