#! /bin/bash
# compress minc files in place
# 
# TODO
#  - compress inplace then move for better performance

RATIO=4

usage ()
{
	echo "Usage: $(basename $0) [-c RATIO] MINCFILE..."
	echo "  -c RATIO      compression ratio, from 0 (disabled) to 9, default $RATIO"
}

while getopts c:v opt
do
	case "$opt" in
		c)  RATIO="$OPTARG";;
		v)  VERBOSE="-v";;
		\?)  usage; exit 1;;
	esac
done
shift $(expr $OPTIND - 1)

[ $# -lt 1 ] && { usage; exit 1; }

[ -z "$TMPDIR" ] && { echo "ERROR: \$TMPDIR not set"; exit 1; }
[ $RATIO -lt 0 -o $RATIO -gt 9 ] && { echo "ERROR: illegal compression ratio"; exit 1; }


TDIR=$TMPDIR/$USER/$$; mkdir -p $TDIR
trap "{ rm -rf $TDIR; exit 255; }" SIGINT SIGTERM


for f in $@; do
	echo "$f"
	[ -f "$f" ] || { echo "ERROR: could not find file: $f" > /dev/stderr; continue; }
	ORIGSIZE=`stat -c%s $f`
	mincconvert -2 -clobber -compress $RATIO $f $TDIR/`basename $f` && cp $TDIR/`basename $f` $f && [ -z "$VERBOSE" ] || printf "compressed \"%s\" with ratio %d to %0.2f%% of original size\n" $f $RATIO `echo "scale=2; $(stat -c%s $f) * 100 / $ORIGSIZE " | bc -l`
done


rm -rf $TDIR
exit 0

